//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PredictDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PredictDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PredictDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 °C 的當地語系化字串。
        /// </summary>
        internal static string Label_CelsiusSymbol {
            get {
                return ResourceManager.GetString("Label_CelsiusSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 % 的當地語系化字串。
        /// </summary>
        internal static string Label_Percentage {
            get {
                return ResourceManager.GetString("Label_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇縣市 的當地語系化字串。
        /// </summary>
        internal static string Label_PleaseSelectACounty {
            get {
                return ResourceManager.GetString("Label_PleaseSelectACounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返回 的當地語系化字串。
        /// </summary>
        internal static string Label_ReturnPage {
            get {
                return ResourceManager.GetString("Label_ReturnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點 的當地語系化字串。
        /// </summary>
        internal static string Label_TimeHour {
            get {
                return ResourceManager.GetString("Label_TimeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 縣市預報 的當地語系化字串。
        /// </summary>
        internal static string Label_TitleCountyForecast {
            get {
                return ResourceManager.GetString("Label_TitleCountyForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 氣象預報 的當地語系化字串。
        /// </summary>
        internal static string Label_WeatherForecast {
            get {
                return ResourceManager.GetString("Label_WeatherForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 南投縣 的當地語系化字串。
        /// </summary>
        internal static string 南投縣 {
            get {
                return ResourceManager.GetString("南投縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 嘉義市 的當地語系化字串。
        /// </summary>
        internal static string 嘉義市 {
            get {
                return ResourceManager.GetString("嘉義市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 嘉義縣 的當地語系化字串。
        /// </summary>
        internal static string 嘉義縣 {
            get {
                return ResourceManager.GetString("嘉義縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 基隆市 的當地語系化字串。
        /// </summary>
        internal static string 基隆市 {
            get {
                return ResourceManager.GetString("基隆市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 宜蘭縣 的當地語系化字串。
        /// </summary>
        internal static string 宜蘭縣 {
            get {
                return ResourceManager.GetString("宜蘭縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 屏東縣 的當地語系化字串。
        /// </summary>
        internal static string 屏東縣 {
            get {
                return ResourceManager.GetString("屏東縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 彰化縣 的當地語系化字串。
        /// </summary>
        internal static string 彰化縣 {
            get {
                return ResourceManager.GetString("彰化縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新北市 的當地語系化字串。
        /// </summary>
        internal static string 新北市 {
            get {
                return ResourceManager.GetString("新北市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新竹市 的當地語系化字串。
        /// </summary>
        internal static string 新竹市 {
            get {
                return ResourceManager.GetString("新竹市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新竹縣 的當地語系化字串。
        /// </summary>
        internal static string 新竹縣 {
            get {
                return ResourceManager.GetString("新竹縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 桃園市 的當地語系化字串。
        /// </summary>
        internal static string 桃園市 {
            get {
                return ResourceManager.GetString("桃園市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 澎湖縣 的當地語系化字串。
        /// </summary>
        internal static string 澎湖縣 {
            get {
                return ResourceManager.GetString("澎湖縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺中市 的當地語系化字串。
        /// </summary>
        internal static string 臺中市 {
            get {
                return ResourceManager.GetString("臺中市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺北市 的當地語系化字串。
        /// </summary>
        internal static string 臺北市 {
            get {
                return ResourceManager.GetString("臺北市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺南市 的當地語系化字串。
        /// </summary>
        internal static string 臺南市 {
            get {
                return ResourceManager.GetString("臺南市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臺東縣 的當地語系化字串。
        /// </summary>
        internal static string 臺東縣 {
            get {
                return ResourceManager.GetString("臺東縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 花蓮縣 的當地語系化字串。
        /// </summary>
        internal static string 花蓮縣 {
            get {
                return ResourceManager.GetString("花蓮縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 苗栗縣 的當地語系化字串。
        /// </summary>
        internal static string 苗栗縣 {
            get {
                return ResourceManager.GetString("苗栗縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連江縣 的當地語系化字串。
        /// </summary>
        internal static string 連江縣 {
            get {
                return ResourceManager.GetString("連江縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金門縣 的當地語系化字串。
        /// </summary>
        internal static string 金門縣 {
            get {
                return ResourceManager.GetString("金門縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 雲林縣 的當地語系化字串。
        /// </summary>
        internal static string 雲林縣 {
            get {
                return ResourceManager.GetString("雲林縣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 高雄市 的當地語系化字串。
        /// </summary>
        internal static string 高雄市 {
            get {
                return ResourceManager.GetString("高雄市", resourceCulture);
            }
        }
    }
}
