//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EarthquakeReportList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EarthquakeReportList() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EarthquakeReportList", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 深度 的當地語系化字串。
        /// </summary>
        internal static string Label_Depth {
            get {
                return ResourceManager.GetString("Label_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地震編號 的當地語系化字串。
        /// </summary>
        internal static string Label_EarthquakeNumber {
            get {
                return ResourceManager.GetString("Label_EarthquakeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公里 的當地語系化字串。
        /// </summary>
        internal static string Label_KilometerDistance {
            get {
                return ResourceManager.GetString("Label_KilometerDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 規模 的當地語系化字串。
        /// </summary>
        internal static string Label_Magnitude {
            get {
                return ResourceManager.GetString("Label_Magnitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新消息 的當地語系化字串。
        /// </summary>
        internal static string Label_News {
            get {
                return ResourceManager.GetString("Label_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地震報告 的當地語系化字串。
        /// </summary>
        internal static string Label_TitleEarthquakeReport {
            get {
                return ResourceManager.GetString("Label_TitleEarthquakeReport", resourceCulture);
            }
        }
    }
}
